-- # =================== START OF LEETCODE 177. Nth Highest Salary ========================================
-- #  this is SQL related done for mysql
-CREATE FUNCTION getNthHighestSalary(N INT) RETURNS INT
-BEGIN
- SET N = N - 1
- RETURN (
-   SELECT DISTINCT salary FROM employee ORDER BY salary DESC LIMIT N,1
-
);
-END
-- # =================== END OF LEETCODE 177. Nth Highest Salary ========================================
